version: '3.4'

services:
  weather:
    image: weather
    container_name: weather
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_Kestrel__Certificates__Default__Password: Pa55w0rd2022
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/https.pfx
      ASPNETCORE_URLS: https://+443;http://+80
    build:
      context: .
      dockerfile: WeatherTest/Dockerfile
    ports:
    - 23712:80
    - 44315:443
    volumes:
      - ~/aspnet/https/:/https:ro
      - ~/AppData/Roaming/ASP.NET/Https/:/root/.aspnet/https